# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analyzer.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBlockSize = QtWidgets.QComboBox(self.centralwidget)
        self.comboBlockSize.setGeometry(QtCore.QRect(120, 15, 181, 25))
        self.comboBlockSize.setCurrentText("")
        self.comboBlockSize.setObjectName("comboBlockSize")
        self.comboBlockSize.addItem("")
        self.comboBlockSize.addItem("")
        self.comboBlockSize.addItem("")
        self.comboBlockSize.addItem("")
        self.comboBlockSize.addItem("")
        self.comboBlockSize.addItem("")
        self.labelBlockLength = QtWidgets.QLabel(self.centralwidget)
        self.labelBlockLength.setGeometry(QtCore.QRect(20, 15, 91, 17))
        self.labelBlockLength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBlockLength.setObjectName("labelBlockLength")
        self.labelWindow = QtWidgets.QLabel(self.centralwidget)
        self.labelWindow.setGeometry(QtCore.QRect(20, 45, 91, 17))
        self.labelWindow.setObjectName("labelWindow")
        self.comboWindow = QtWidgets.QComboBox(self.centralwidget)
        self.comboWindow.setGeometry(QtCore.QRect(120, 45, 181, 25))
        self.comboWindow.setCurrentText("")
        self.comboWindow.setObjectName("comboWindow")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.comboWindow.addItem("")
        self.labelSmoothing = QtWidgets.QLabel(self.centralwidget)
        self.labelSmoothing.setGeometry(QtCore.QRect(20, 75, 91, 17))
        self.labelSmoothing.setObjectName("labelSmoothing")
        self.labelOverlap = QtWidgets.QLabel(self.centralwidget)
        self.labelOverlap.setGeometry(QtCore.QRect(420, 15, 61, 20))
        self.labelOverlap.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOverlap.setObjectName("labelOverlap")
        self.comboSmoothing = QtWidgets.QComboBox(self.centralwidget)
        self.comboSmoothing.setGeometry(QtCore.QRect(120, 75, 181, 25))
        self.comboSmoothing.setCurrentText("")
        self.comboSmoothing.setObjectName("comboSmoothing")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.comboSmoothing.addItem("")
        self.dialAverageTime = QtWidgets.QDial(self.centralwidget)
        self.dialAverageTime.setGeometry(QtCore.QRect(330, 35, 50, 51))
        self.dialAverageTime.setMaximum(5000)
        self.dialAverageTime.setPageStep(100)
        self.dialAverageTime.setObjectName("dialAverageTime")
        self.labelAverageTime = QtWidgets.QLabel(self.centralwidget)
        self.labelAverageTime.setGeometry(QtCore.QRect(330, 15, 61, 17))
        self.labelAverageTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelAverageTime.setObjectName("labelAverageTime")
        self.labelAverageTimeValue = QtWidgets.QLabel(self.centralwidget)
        self.labelAverageTimeValue.setGeometry(QtCore.QRect(330, 85, 51, 17))
        self.labelAverageTimeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAverageTimeValue.setObjectName("labelAverageTimeValue")
        self.labelOverlapValue = QtWidgets.QLabel(self.centralwidget)
        self.labelOverlapValue.setGeometry(QtCore.QRect(420, 85, 51, 17))
        self.labelOverlapValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOverlapValue.setObjectName("labelOverlapValue")
        self.dialOverlap = QtWidgets.QDial(self.centralwidget)
        self.dialOverlap.setGeometry(QtCore.QRect(420, 35, 50, 51))
        self.dialOverlap.setMaximum(50)
        self.dialOverlap.setPageStep(5)
        self.dialOverlap.setObjectName("dialOverlap")
        self.dialNumberPeaks = QtWidgets.QDial(self.centralwidget)
        self.dialNumberPeaks.setGeometry(QtCore.QRect(330, 125, 50, 51))
        self.dialNumberPeaks.setMinimum(1)
        self.dialNumberPeaks.setMaximum(20)
        self.dialNumberPeaks.setPageStep(5)
        self.dialNumberPeaks.setProperty("value", 1)
        self.dialNumberPeaks.setObjectName("dialNumberPeaks")
        self.labelNumberPeaksValue = QtWidgets.QLabel(self.centralwidget)
        self.labelNumberPeaksValue.setGeometry(QtCore.QRect(330, 175, 51, 17))
        self.labelNumberPeaksValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNumberPeaksValue.setObjectName("labelNumberPeaksValue")
        self.labelNumberPeaks = QtWidgets.QLabel(self.centralwidget)
        self.labelNumberPeaks.setGeometry(QtCore.QRect(330, 105, 61, 20))
        self.labelNumberPeaks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelNumberPeaks.setObjectName("labelNumberPeaks")
        self.labelFs = QtWidgets.QLabel(self.centralwidget)
        self.labelFs.setGeometry(QtCore.QRect(20, 105, 91, 17))
        self.labelFs.setObjectName("labelFs")
        self.comboFS = QtWidgets.QComboBox(self.centralwidget)
        self.comboFS.setGeometry(QtCore.QRect(120, 105, 181, 25))
        self.comboFS.setCurrentText("")
        self.comboFS.setObjectName("comboFS")
        self.comboFS.addItem("")
        self.comboFS.addItem("")
        self.labelPeakThreshValue = QtWidgets.QLabel(self.centralwidget)
        self.labelPeakThreshValue.setGeometry(QtCore.QRect(420, 175, 51, 17))
        self.labelPeakThreshValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPeakThreshValue.setObjectName("labelPeakThreshValue")
        self.dialPeakThresh = QtWidgets.QDial(self.centralwidget)
        self.dialPeakThresh.setGeometry(QtCore.QRect(420, 125, 50, 51))
        self.dialPeakThresh.setMinimum(-120)
        self.dialPeakThresh.setMaximum(0)
        self.dialPeakThresh.setPageStep(10)
        self.dialPeakThresh.setProperty("value", -120)
        self.dialPeakThresh.setObjectName("dialPeakThresh")
        self.labelPeakThresh = QtWidgets.QLabel(self.centralwidget)
        self.labelPeakThresh.setGeometry(QtCore.QRect(420, 105, 51, 20))
        self.labelPeakThresh.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPeakThresh.setObjectName("labelPeakThresh")
        self.labelAudioIF = QtWidgets.QLabel(self.centralwidget)
        self.labelAudioIF.setGeometry(QtCore.QRect(20, 135, 91, 17))
        self.labelAudioIF.setObjectName("labelAudioIF")
        self.comboAudioIF = QtWidgets.QComboBox(self.centralwidget)
        self.comboAudioIF.setGeometry(QtCore.QRect(120, 135, 181, 25))
        self.comboAudioIF.setCurrentText("")
        self.comboAudioIF.setObjectName("comboAudioIF")
        self.labelRunMode = QtWidgets.QLabel(self.centralwidget)
        self.labelRunMode.setGeometry(QtCore.QRect(20, 195, 91, 17))
        self.labelRunMode.setObjectName("labelRunMode")
        self.comboRunMode = QtWidgets.QComboBox(self.centralwidget)
        self.comboRunMode.setGeometry(QtCore.QRect(120, 195, 181, 25))
        self.comboRunMode.setCurrentText("")
        self.comboRunMode.setObjectName("comboRunMode")
        self.comboRunMode.addItem("")
        self.comboRunMode.addItem("")
        self.comboRunMode.addItem("")
        self.comboRunMode.addItem("")
        self.comboRunMode.addItem("")
        self.comboRunMode.addItem("")
        self.labelAudioCh = QtWidgets.QLabel(self.centralwidget)
        self.labelAudioCh.setGeometry(QtCore.QRect(20, 165, 91, 17))
        self.labelAudioCh.setObjectName("labelAudioCh")
        self.comboAudioCh = QtWidgets.QComboBox(self.centralwidget)
        self.comboAudioCh.setGeometry(QtCore.QRect(120, 165, 181, 25))
        self.comboAudioCh.setCurrentText("")
        self.comboAudioCh.setObjectName("comboAudioCh")
        self.labelTestFile = QtWidgets.QLabel(self.centralwidget)
        self.labelTestFile.setGeometry(QtCore.QRect(20, 225, 91, 31))
        self.labelTestFile.setObjectName("labelTestFile")
        self.txtTestFile = QtWidgets.QTextEdit(self.centralwidget)
        self.txtTestFile.setGeometry(QtCore.QRect(120, 225, 181, 31))
        self.txtTestFile.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.txtTestFile.setReadOnly(True)
        self.txtTestFile.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtTestFile.setPlaceholderText("")
        self.txtTestFile.setObjectName("txtTestFile")
        self.btnOpenTestFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenTestFile.setGeometry(QtCore.QRect(310, 225, 51, 31))
        self.btnOpenTestFile.setObjectName("btnOpenTestFile")
        self.btnPlayPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlayPause.setGeometry(QtCore.QRect(380, 225, 161, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 204, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(117, 231, 9))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 192, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 103, 4))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 77, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.btnPlayPause.setPalette(palette)
        self.btnPlayPause.setObjectName("btnPlayPause")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 290, 821, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutContentMpl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutContentMpl.setContentsMargins(0, 0, 0, 0)
        self.layoutContentMpl.setSpacing(0)
        self.layoutContentMpl.setObjectName("layoutContentMpl")
        self.dialInputGain = QtWidgets.QDial(self.centralwidget)
        self.dialInputGain.setGeometry(QtCore.QRect(500, 35, 50, 51))
        self.dialInputGain.setMinimum(-120)
        self.dialInputGain.setMaximum(10)
        self.dialInputGain.setPageStep(10)
        self.dialInputGain.setObjectName("dialInputGain")
        self.labelInputGainValue = QtWidgets.QLabel(self.centralwidget)
        self.labelInputGainValue.setGeometry(QtCore.QRect(500, 85, 51, 17))
        self.labelInputGainValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInputGainValue.setObjectName("labelInputGainValue")
        self.labelInputGain = QtWidgets.QLabel(self.centralwidget)
        self.labelInputGain.setGeometry(QtCore.QRect(500, 15, 61, 20))
        self.labelInputGain.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelInputGain.setObjectName("labelInputGain")
        self.sliderWavPlayer = QtWidgets.QSlider(self.centralwidget)
        self.sliderWavPlayer.setGeometry(QtCore.QRect(120, 265, 181, 16))
        self.sliderWavPlayer.setMaximum(999)
        self.sliderWavPlayer.setOrientation(QtCore.Qt.Horizontal)
        self.sliderWavPlayer.setObjectName("sliderWavPlayer")
        self.labelWavPlayer = QtWidgets.QLabel(self.centralwidget)
        self.labelWavPlayer.setGeometry(QtCore.QRect(310, 262, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelWavPlayer.setFont(font)
        self.labelWavPlayer.setObjectName("labelWavPlayer")
        self.labelTestParam = QtWidgets.QLabel(self.centralwidget)
        self.labelTestParam.setGeometry(QtCore.QRect(510, 105, 71, 20))
        self.labelTestParam.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelTestParam.setObjectName("labelTestParam")
        self.labelTestParamValue = QtWidgets.QLabel(self.centralwidget)
        self.labelTestParamValue.setGeometry(QtCore.QRect(500, 175, 51, 17))
        self.labelTestParamValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTestParamValue.setObjectName("labelTestParamValue")
        self.dialTestParam = QtWidgets.QDial(self.centralwidget)
        self.dialTestParam.setGeometry(QtCore.QRect(500, 125, 50, 51))
        self.dialTestParam.setMinimum(20)
        self.dialTestParam.setMaximum(20000)
        self.dialTestParam.setPageStep(50)
        self.dialTestParam.setProperty("value", 20)
        self.dialTestParam.setSliderPosition(20)
        self.dialTestParam.setObjectName("dialTestParam")
        self.checkboxPeaks = QtWidgets.QCheckBox(self.centralwidget)
        self.checkboxPeaks.setGeometry(QtCore.QRect(390, 260, 71, 23))
        self.checkboxPeaks.setObjectName("checkboxPeaks")
        self.checkboxShadows = QtWidgets.QCheckBox(self.centralwidget)
        self.checkboxShadows.setGeometry(QtCore.QRect(480, 260, 61, 23))
        self.checkboxShadows.setObjectName("checkboxShadows")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.comboBlockSize.setCurrentIndex(-1)
        self.comboWindow.setCurrentIndex(-1)
        self.comboSmoothing.setCurrentIndex(-1)
        self.comboFS.setCurrentIndex(-1)
        self.comboRunMode.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PolyTune"))
        self.comboBlockSize.setItemText(0, _translate("MainWindow", "128"))
        self.comboBlockSize.setItemText(1, _translate("MainWindow", "256"))
        self.comboBlockSize.setItemText(2, _translate("MainWindow", "512"))
        self.comboBlockSize.setItemText(3, _translate("MainWindow", "1024"))
        self.comboBlockSize.setItemText(4, _translate("MainWindow", "2048"))
        self.comboBlockSize.setItemText(5, _translate("MainWindow", "4096"))
        self.labelBlockLength.setText(_translate("MainWindow", "Block Length"))
        self.labelWindow.setText(_translate("MainWindow", "Window"))
        self.comboWindow.setItemText(0, _translate("MainWindow", "Rectangular"))
        self.comboWindow.setItemText(1, _translate("MainWindow", "Hanning"))
        self.comboWindow.setItemText(2, _translate("MainWindow", "Hamming"))
        self.comboWindow.setItemText(3, _translate("MainWindow", "Bartlett"))
        self.comboWindow.setItemText(4, _translate("MainWindow", "Blackman"))
        self.comboWindow.setItemText(5, _translate("MainWindow", "Flattop"))
        self.comboWindow.setItemText(6, _translate("MainWindow", "Gaussian"))
        self.comboWindow.setItemText(7, _translate("MainWindow", "Kaiser"))
        self.labelSmoothing.setText(_translate("MainWindow", "Smoothing"))
        self.labelOverlap.setText(_translate("MainWindow", "Overlap"))
        self.comboSmoothing.setItemText(0, _translate("MainWindow", "OFF"))
        self.comboSmoothing.setItemText(1, _translate("MainWindow", "1/6 OCT"))
        self.comboSmoothing.setItemText(2, _translate("MainWindow", "1/5 OCT"))
        self.comboSmoothing.setItemText(3, _translate("MainWindow", "1/4 OCT"))
        self.comboSmoothing.setItemText(4, _translate("MainWindow", "1/3 OCT"))
        self.comboSmoothing.setItemText(5, _translate("MainWindow", "1/2 OCT"))
        self.comboSmoothing.setItemText(6, _translate("MainWindow", "2/3 OCT"))
        self.comboSmoothing.setItemText(7, _translate("MainWindow", "3/4 OCT"))
        self.comboSmoothing.setItemText(8, _translate("MainWindow", "1 OCT"))
        self.comboSmoothing.setItemText(9, _translate("MainWindow", "3/2 OCT"))
        self.comboSmoothing.setItemText(10, _translate("MainWindow", "2 OCT"))
        self.comboSmoothing.setItemText(11, _translate("MainWindow", "5/2 OCT"))
        self.comboSmoothing.setItemText(12, _translate("MainWindow", "1/9 OCT"))
        self.comboSmoothing.setItemText(13, _translate("MainWindow", "1/12 OCT"))
        self.labelAverageTime.setText(_translate("MainWindow", "Avg (ms)"))
        self.labelAverageTimeValue.setText(_translate("MainWindow", "0"))
        self.labelOverlapValue.setText(_translate("MainWindow", "0"))
        self.labelNumberPeaksValue.setText(_translate("MainWindow", "1"))
        self.labelNumberPeaks.setText(_translate("MainWindow", "N Peaks"))
        self.labelFs.setText(_translate("MainWindow", "FS"))
        self.comboFS.setItemText(0, _translate("MainWindow", "44100 Hz"))
        self.comboFS.setItemText(1, _translate("MainWindow", "48000 Hz"))
        self.labelPeakThreshValue.setText(_translate("MainWindow", "-120"))
        self.labelPeakThresh.setText(_translate("MainWindow", "Thresh"))
        self.labelAudioIF.setText(_translate("MainWindow", "Audio IF"))
        self.labelRunMode.setText(_translate("MainWindow", "Run Mode"))
        self.comboRunMode.setItemText(0, _translate("MainWindow", "Test Multisine"))
        self.comboRunMode.setItemText(1, _translate("MainWindow", "Test White Noise"))
        self.comboRunMode.setItemText(2, _translate("MainWindow", "Test Square"))
        self.comboRunMode.setItemText(3, _translate("MainWindow", "Test Sawtooth"))
        self.comboRunMode.setItemText(4, _translate("MainWindow", "WAV File"))
        self.comboRunMode.setItemText(5, _translate("MainWindow", "Stream"))
        self.labelAudioCh.setText(_translate("MainWindow", "Audio Ch"))
        self.labelTestFile.setText(_translate("MainWindow", "Test File"))
        self.btnOpenTestFile.setText(_translate("MainWindow", "Open"))
        self.btnPlayPause.setText(_translate("MainWindow", "Play"))
        self.labelInputGainValue.setText(_translate("MainWindow", "0"))
        self.labelInputGain.setText(_translate("MainWindow", "In Gain"))
        self.labelWavPlayer.setText(_translate("MainWindow", "00:00/00:00"))
        self.labelTestParam.setText(_translate("MainWindow", "Freq"))
        self.labelTestParamValue.setText(_translate("MainWindow", "20"))
        self.checkboxPeaks.setText(_translate("MainWindow", "Peaks"))
        self.checkboxShadows.setText(_translate("MainWindow", "Lines"))
